### ISSUE TITLE
사이드바 구현

### ISSUE THREAD

**Issue by SinJeongEun** [skhuCloud/skhuCloud#42]
- [x] 한개 선택시 버전 조회
- [x] 사이드바 내부 정렬 조정
- [x] 두개 선택시 reateMokService.createMokFolderDiffDtoList() 호출 (파일버전)
- [x] 해당 폴더의 버전 2개 선택 시

**Comment by kpeel5839** [comment]
> 한개 선택시 버전 조회 두개 선택시 reateMokService.createMokFolderDiffDtoList() 호출

Good
